---
title: "Part 2.COVID-19 Situation in Japan"
description: |
  In this section of the blog, we will drive deeper to explore the action that has been taken into account to fight COVID-19 in Japan by looking at it's COVID-19 recovery rate, and the vacinnation rate.
author:
  - name: Qin Xu
    url: {}
date: 09-02-2021
output:
  distill::distill_article:
    self_contained: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE)
```

```{r library}
library(tidyverse)
library(gt)
library(formattable)
library(here)
library(kableExtra)
library(ggplot2)
library(plotly)
```

```{r read_data}
recovery_data <- read.csv(here::here("data/recovery_total.csv"))
japan_data <- read.csv(here::here("data/owid-covid-data.csv"))
prefectures_data <- read.csv(here::here("data/prefectures.csv"))
```

```{r}
prefectures <- prefectures_data %>%
  select(c(
  "prefectureNameE",
  "testedPositive",
  "peopleTested")) %>% 
  group_by(prefectureNameE) %>% 
  summarise (postive_cases = sum(testedPositive)) %>% 
  arrange(desc(postive_cases)) 

```





```{r vacination}
vac<- japan_data %>% 
  select(c("date",
           "total_vaccinations",
           "people_fully_vaccinated",
           "people_vaccinated",
           "new_vaccinations",
           "population",
           "location")) %>% 
  filter (location == "Japan") %>% 
  mutate(date = as.Date(date)) %>% 
  group_by(date) %>% 
mutate(full_vacination_rate = sum(people_fully_vaccinated/population, na.rm = TRUE),
         vacination_rate = sum(people_vaccinated/population, na.rm = TRUE))
```

```{r table}
vac_table <- vac %>%  
  select(c("vacination_rate","full_vacination_rate","date")) %>% 
  filter (date == "2021-08-30" |date == "2021-01-30" | date == "2021-03-30" |date == "2021-04-30" | date == "2021-05-30" |date == "2021-06-30" | date == "2021-07-30")%>% 
    relocate(date,.before = vacination_rate) %>% 
  gt() %>% 
  tab_header (title = "The Vacination rate in Japan",
              subtitle = "The vacination rate and fully vacination rate 2020 vs 2021 in Japan ") %>% 
 tab_source_note(md("Souced:COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University (JHU)"))
vac_table

```


```{r plot}
vac_plot<- vac %>% 
  select(c("vacination_rate","full_vacination_rate","date"))

full_v<- ggplot(data = vac_plot, 
                      aes(x = date,
                          y = vacination_rate
                          )) +
    geom_bar(stat = "identity", size = 0.5) +
    ggtitle("People_full_vaccinated proportion in Japan from 2020-2021") +
  xlab("Date") + 
  ylab("Percentage") +
   scale_colour_brewer(palette = "Set1")

 fullyv_p<-ggplotly(full_v)
 fullyv_p
```



```{r recovery}
japan_recovery <- recovery_data %>% 
  rename("Number_of_recovery" = "recovery_total") %>%  
  mutate(Date = as.Date(Date)) 
```

```{r recovery_graph}
recovery_graph<- ggplot(data = japan_recovery, 
                      aes(x = Date,
                          y= Number_of_recovery,
                          )) +
    geom_line(stat = "identity", size = 0.5) +
  geom_point(size = 0.3) +
    ggtitle("Total number of COVID-19 recoveries in Japn from 2020-2021") +
  xlab("Date") + 
  ylab("Number of recovery in Japan (cumulatively)") +
   scale_colour_brewer(palette = "Set1")

recovery_p <-ggplotly(recovery_graph)
recovery_p
```

