---
title: "Part 1-Covid-19 Situation in Japan "
description: |
  In this section of the blog, we will be examine the effect of COVID-19 in Japan through detail analysis of the number of death, the number of recoverys and the future trend of COVID-19 in Japan  .
author:
  - name: Qin Xu 
    url: 
date: 09-01-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE)
```

```{r library}
library(tidyverse)
library(gt)
library(formattable)
library(here)
library(kableExtra)
library(ggplot2)
library(plotly)

```

# Death caused by covid-19 in Japan 

```{r read_death}
death_data <- read.csv(here::here("data/death_total.csv"))
recovery_data <- read.csv(here::here("data/recovery_total.csv"))
```

```{r death}
japan_death <- death_data %>% 
  rename("date" = "日付",
         "Number_of_death" = "死亡者数") %>% 
  mutate(date = as.Date(date)) 
```

```{r death_graph}
death_graph<- ggplot(data = japan_death, 
                      aes(x = date,
                          y= Number_of_death,
                          )) +
    geom_line(stat = "identity", size = 0.5) +
  geom_point(size = 0.3) +
    ggtitle("Total number of COVID-19 Death in Japn from 2020-2021") +
  xlab("Date") + 
  ylab("Number of death in Japan (cumulatively)") +
   scale_colour_brewer(palette = "Set1")

death_p <-ggplotly(death_graph)
death_p  


```

```{r recovery}
japan_recovery <- recovery_data %>% 
  rename("Number_of_recovery" = "recovery_total") %>%  
  mutate(Date = as.Date(Date)) 
```

```{r recovery_graph}
recovery_graph<- ggplot(data = japan_recovery, 
                      aes(x = Date,
                          y= Number_of_recovery,
                          )) +
    geom_line(stat = "identity", size = 0.5) +
  geom_point(size = 0.3) +
    ggtitle("Total number of COVID-19 recoveries in Japn from 2020-2021") +
  xlab("Date") + 
  ylab("Number of recovery in Japan (cumulatively)") +
   scale_colour_brewer(palette = "Set1")

recovery_p <-ggplotly(recovery_graph)
recovery_p
```

 